# Generated by Django 3.2.3 on 2021-06-17 10:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('mvId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('mvName', models.CharField(max_length=200, null=True)),
                ('mvData', models.TextField(null=True)),
                ('mvYear', models.CharField(max_length=20, null=True)),
                ('mvPoster', models.ImageField(null=True, upload_to='movie')),
                ('mvcloud', models.ImageField(null=True, upload_to='movie')),
                ('mv_createdate', models.DateField(default=django.utils.timezone.now)),
                ('mvLocation', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
