# Generated by Django 3.2.3 on 2021-05-17 18:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='mv_createdate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
