# Generated by Django 3.2.3 on 2021-06-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20210617_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='mvPoster',
            field=models.ImageField(null=True, upload_to='media/poster'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='mvcloud',
            field=models.ImageField(null=True, upload_to='media/cloudimg'),
        ),
    ]
