# Generated by Django 3.2.3 on 2021-06-17 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20210617_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='mvLocation',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
