# Generated by Django 3.2.3 on 2021-06-17 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_alter_movie_mvlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='mvPoster',
            field=models.ImageField(null=True, upload_to='poster'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='mvcloud',
            field=models.ImageField(null=True, upload_to='cloudimg'),
        ),
    ]
