# Generated by Django 3.2.3 on 2021-06-17 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_auto_20210618_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='mvPoster',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='mvcloud',
            field=models.TextField(null=True),
        ),
    ]
