# Generated by Django 3.2.3 on 2021-06-18 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_alter_movie_mvlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cldImgPath',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='pstImgPath',
            field=models.TextField(null=True),
        ),
    ]
